# Generated by Django 5.2.9 on 2025-12-16 23:31

import sanaap.docs.enums
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True)),
                ('bucket', models.CharField(db_index=True, default='documents', max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('size', models.BigIntegerField()),
                ('mimetype', models.CharField(max_length=255)),
                ('etag', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=sanaap.docs.enums.DocStatus.choices, db_index=True, default=sanaap.docs.enums.DocStatus['ACTIVE'], max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('logs', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-created_at'],
                'default_permissions': ('read', 'write', 'delete'),
                'indexes': [models.Index(fields=['uuid', 'status'], name='docs_docume_uuid_2e7a56_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', sanaap.docs.enums.DocStatus['ACTIVE'])), fields=('uuid',), name='uniq_active_uuid'), models.UniqueConstraint(condition=models.Q(('status', sanaap.docs.enums.DocStatus['ACTIVE'])), fields=('bucket', 'name'), name='uniq_active_doc_name')],
            },
        ),
    ]
